export const effectSafetyRuleNames = [
  'effect-no-floating-effect',
  'effect-require-yield-star',
  'effect-require-return-yield-star',
  'effect-no-floating-fiber',
  'effect-require-suspend-for-recursion',
  'effect-no-silent-error-swallowing',
  'effect-require-typed-error-in-trypromise',
  'effect-require-error-cause-preserved',
  'effect-no-runfork-without-observer',
  'effect-require-acquire-release',
  'effect-require-scoped-for-acquireRelease',
  'effect-require-scoped-for-resources',
  'effect-no-fork-daemon-without-cleanup',
  'effect-require-restore-for-fork-in-uninterruptible',
  'effect-require-bounded-concurrency',
  'effect-require-bounded-flatMap-concurrency',
  'effect-no-unbounded-queue',
  'effect-no-unbounded-stream-buffer',
] as const;

export const effectDefaultRuleNames = [
  'effect-no-floating-effect',
  'effect-require-yield-star',
  'effect-require-return-yield-star',
  'effect-no-floating-fiber',
  'effect-require-suspend-for-recursion',
  'effect-no-silent-error-swallowing',
  'effect-require-typed-error-in-trypromise',
  'effect-require-error-cause-preserved',
  'effect-no-runfork-without-observer',
  'effect-require-acquire-release',
  'effect-require-scoped-for-acquireRelease',
  'effect-require-scoped-for-resources',
  'effect-no-fork-daemon-without-cleanup',
  'effect-require-restore-for-fork-in-uninterruptible',
  'effect-require-bounded-concurrency',
  'effect-require-bounded-flatMap-concurrency',
  'effect-no-unbounded-queue',
  'effect-no-unbounded-stream-buffer',
  'effect-no-focused-effect-tests',
  'effect-no-skipped-effect-tests',
  'effect-no-known-fake-api',
  'effect-require-service-self-match',
  'effect-no-catchAll-with-mapError',
  'effect-prefer-effect-void',
  'effect-prefer-asVoid',
  'effect-prefer-flatMap-over-map-flatten',
  'effect-prefer-succeed-for-static-layers',
  'effect-prefer-schema-tagged-struct',
  'effect-prefer-single-schema-literal-union',
  'effect-schema-require-parseJson-for-json-strings',
  'effect-schema-no-cast-after-decode',
  'effect-no-error-channel-widening-to-unknown',
  'effect-require-service-class-pattern',
  'effect-require-deterministic-service-keys',
] as const;

export const effectStrictRuleNames = ['effect-no-runSync-in-server-request-handlers'] as const;
