[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "deny"
unused_must_use = "deny"
unused_mut = "deny"
unused_crate_dependencies = "deny"

[lints.clippy]
wildcard_enum_match_arm = "deny"
print_stdout = "deny"
print_stderr = "deny"
todo = "deny"
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
unwrap_used = "deny"
expect_used = "deny"
unused_result_ok = "deny"
as_conversions = "deny"
too_many_lines = "deny"
